blueprint:
  name: SpeedTest
  description: SpeedTest Blueprint by Dziban
  version: '1.1.3'
  type: page
  custom_cards:
  - mini-graph-card
card:
  type: custom:dwains-flexbox-card
  items_classes: col-xs-12 col-sm-6 col-sm-6 col-md-4
  cards:
  - type: custom:mini-graph-card
    entities:
    - sensor.speedtest_download
    name: Download
    hours_to_show: 168
    hour24: true
    height: 250
    show_state: true
    state_adaptive_color: true
    points_per_hour: 1
    line_width: 4
    smoothing: true
    show:
      points: true
      graph: line
      extrema: true
    color_thresholds:
    - value: 0
      color: '#ff0000'
    - value: 200
      color: '#ffff00'
    - value: 400
      color: '#00ff00'
    - value: 600
      color: '#00ffff'
    - value: 1000
      color: '#0000ff'
  - type: custom:mini-graph-card
    entities:
    - sensor.speedtest_upload
    name: Upload
    hours_to_show: 168
    hour24: true
    height: 250
    show_state: true
    state_adaptive_color: true
    points_per_hour: 1
    line_width: 4
    smoothing: true
    show:
      points: true
      graph: line
      extrema: true
    color_thresholds:
    - value: 0
      color: '#ff0000'
    - value: 200
      color: '#ffff00'
    - value: 400
      color: '#00ff00'
    - value: 600
      color: '#00ffff'
    - value: 1000
      color: '#0000ff'
  - type: custom:mini-graph-card
    entities:
    - sensor.speedtest_ping
    name: Ping
    hours_to_show: 168
    hour24: true
    height: 250
    show_state: true
    state_adaptive_color: true
    points_per_hour: 1
    line_width: 4
    smoothing: true
    show:
      points: true
      graph: line
      extrema: true
    color_thresholds:
    - value: 200
      color: '#ff0000'
    - value: 50
      color: '#ffff00'
    - value: 30
      color: '#00ff00'
    - value: 10
      color: '#00ffff'
    - value: 0
      color: '#0000ff'
